services:
  backstage:
    build:
      context: .
      dockerfile: Dockerfile
    image: idp-portal
    ports:
      - "7007:7007"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-"5432"}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
